### ISSUE TITLE
Error when editing existing content (Uncaught TypeError: H5P.Version is not a constructor)

### ISSUE THREAD

**Issue by thdebay** [EscolaLMS/H5P#189]
Hello,

I have repeated errors when I work with existing content (created in the H5P editor for Wordpress).

I initially imported my h5p files using the `upload()` method from the `H5PContentRepositoryContract`. I manage to preview the content, but I have an error when I try to edit and save : 
```
Uncaught TypeError: H5P.Version is not a constructor
```

I also attempted to import the .h5p file using the "upload" form provided in the demo app. It does not work and I have this error :
```
Uncaught TypeError: H5P.Question is undefined
```

Do you have any idea where this might come from?

**Comment by qunabu** [comment]
@thdebay can you share privately sample file you're using for us to debug ?

**Comment by thdebay** [comment]
Not a problem, here is one of the files I used when I ran into the issue (zipped)
[actu-50-village-chinois-a-248.h5p.zip](https://github.com/EscolaLMS/H5P/files/11016775/actu-50-village-chinois-a-248.h5p.zip)

**Comment by qunabu** [comment]
Have just uploaded the h5p which was inside the zip in our public demo 
![image](https://user-images.githubusercontent.com/214608/226317358-b519eb1f-27f4-438e-a78e-6627feaca127.png)
https://h5p-laravel-demo.stage.etd24.pl/player/98bb7617-6ef6-4b35-8644-152ccd7025ae

This seems to be be workinG ?

**Comment by thdebay** [comment]
The player is working but the error occurs when you try to edit the h5p and save it

**Comment by qunabu** [comment]
I can confirm that I'm able to reproduce this error 
![image](https://user-images.githubusercontent.com/214608/226421492-9a22d3cb-4cff-4a15-82b2-4daf9c1c270d.png)
