### ISSUE TITLE
Add other languages?

### ISSUE THREAD

**Issue by rocky0414** [EscolaLMS/H5P#196]
I found the pl and pl.json folder under /vendor/escolalms/headless-h5p/resources/lang. How can I add languages such as de here so that e.g. .../api/admin/hh5p/editor?lang=de can be called?

**Comment by qunabu** [comment]
@Haxikowy can you help here please ?

**Comment by rocky0414** [comment]
I would like to use it. I have tested it and it makes a good impression. The last hurdle would be to import the translations.
