### ISSUE TITLE
H5P Report for all User Interactive

### ISSUE THREAD

**Issue by MahmoudSaidHaggag** [EscolaLMS/H5P#212]
I want to display list of users with their solutions for H5P content and display H5P content as specific user data such as

![Screenshot from 2024-07-29 06-26-41](https://github.com/user-attachments/assets/9d56b91f-8dca-4fbf-b566-e89c6fb78f15)
![Screenshot from 2024-07-29 06-27-10](https://github.com/user-attachments/assets/886262b5-7461-472a-8a4a-e143db3c9c20)
![Screenshot from 2024-07-29 06-27-47](https://github.com/user-attachments/assets/eb9e0513-f6f4-4510-a7d3-e678f25760fb)

Please can help me

**Comment by qunabu** [comment]
you would like to get access to this kind of reports in admin panel 
related to https://h5p.org/documentation/for-authors/analyzing-results-and-answers ? 

ps. what is reporting software you attached screenshots ?

**Comment by qunabu** [comment]
@MahmoudSaidHaggag h5p is sending xAPI data which you can consume with LRS, we use https://traxlrs.com/ 
but it doesn't have any build in feature like h5p.com has - this is their premium feature. 

Although all the data is stored in LRS you would need just to build a visual layer on that
