### ISSUE TITLE
swagger missing padlocks

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/H5P#82]
annotate which endpoints require authorisation 
<img width="1583" alt="Screenshot 2022-02-07 at 11 01 12" src="https://user-images.githubusercontent.com/214608/152766485-9d259594-9e82-4984-a62d-0d600feb36ce.png">

**Comment by KrzysztofDziedziechEscolasoft** [comment]
https://i.imgur.com/DQKdkPt.png
